name: first_protection
description: "Flutter Protection Project"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  shared_preferences: ^2.2.2
  cloud_firestore: ^4.14.0
  permission_handler: ^12.0.0+1
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.8
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.1.1

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/logo-first-protection.jpeg" 

flutter:

  uses-material-design: true

  assets:
     - assets/images/logo-first-protection.jpeg
     - assets/images/carbonfiber.jpg
     - assets/images/banner-first-protection.png
     - assets/images/btn-humo-activado.png
     - assets/images/btn-cortacorriente-activado.png
     - assets/images/btn-audio-activado.png
