// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCX2yzvc1AfNQu_szT6DZpRYeIWlQ56stc',
    appId: '1:508596165428:web:735566b9a8b9188ccda361',
    messagingSenderId: '508596165428',
    projectId: 'first-protection',
    authDomain: 'first-protection.firebaseapp.com',
    databaseURL: 'https://first-protection-default-rtdb.firebaseio.com',
    storageBucket: 'first-protection.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-1djkmEwwVVKO5OChrqRpS5Ed6Rb6P8A',
    appId: '1:508596165428:android:9c0e7ec6e7488c93cda361',
    messagingSenderId: '508596165428',
    projectId: 'first-protection',
    databaseURL: 'https://first-protection-default-rtdb.firebaseio.com',
    storageBucket: 'first-protection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkwX5-KEL_Q2zDGc4hFVISpPaMTLqRTa4',
    appId: '1:508596165428:ios:d664a0cf44a258dacda361',
    messagingSenderId: '508596165428',
    projectId: 'first-protection',
    databaseURL: 'https://first-protection-default-rtdb.firebaseio.com',
    storageBucket: 'first-protection.firebasestorage.app',
    iosBundleId: 'com.firstprotection.firstProtection',
  );
}
